### BeautifulSoup 
* select() 함수 사용
* melon 100 chart 데이터 파싱

In [ ]:
import re
import requests
from bs4 import BeautifulSoup

url = 'https://www.melon.com/chart/index.htm'

headers = {
    'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36'
}

# 노래 상세정보 song_url = f'https://www.melon.com/song/detail.htm?songId={song_id}'

res = requests.get(url, headers=headers) #스크래핑 한것과 동일함
if not res.ok:
        print(f'Error code = {res.status_code}')
        exit()
soup = BeautifulSoup(res.text, 'html.parser') # res.text html 문자를 파싱 가능한 beautifulSoup 객체로 변환
# <div class="wrap_song_info"> 
#   <a href="javascript:melon.play.playSong('1000002721',37928381);" title="LOVE ATTACK 재생">LOVE ATTACK</a>
atag_list = soup.select("div.wrap_song_info a[href*='playSong']")
print(len(atag_list))  #몇개의 곡 링크가 찾아졌나?

# 100곡의 song list
song_list = [] #100곡의 정보를 담을 빈 리스트를 생성
for idx,atag in enumerate(atag_list,1): #atag_list를 순회함, enumerate idx를 1부터 부여함
    song_dict ={} #1곡 song dict
    song_dict['title'] =atag.text #1곡 제목
    href = atag['href'] #a태그의 href 속성을 가져옴
    matched = re.search(r'(\d+)\);',href) #href 안에서 숫자가 1개 이상 연속된 부분을 캡쳐 그룹으로 저장
    if matched:
        song_id = matched.group(1) #정규식의 첫번째 괄호로 캡처된 부분만 추출
    song_dict['id'] = song_id #추출한 곡 id를 딕셔너리에 저장
    
    song_url = f'https://www.melon.com/song/detail.htm?songId={song_id}' #song_id를 활용해서 url 조합함
    song_dict['url'] = song_url  #완성된 상세페이지 url을 딕셔너리에 저장
    print(f'{idx}={song_dict}')

    song_list.append(song_dict) #song_dict를 song_list에 추가함

100
1={'title': 'LOVE ATTACK', 'id': '37928381', 'url': 'https://www.melon.com/song/detail.htm?songId=37928381'}
2={'title': '갑자기', 'id': '602024048', 'url': 'https://www.melon.com/song/detail.htm?songId=602024048'}
3={'title': 'REDRED', 'id': '601807965', 'url': 'https://www.melon.com/song/detail.htm?songId=601807965'}
4={'title': 'LEMONADE', 'id': '602115220', 'url': 'https://www.melon.com/song/detail.htm?songId=602115220'}
5={'title': 'Pretty Girl', 'id': '602450078', 'url': 'https://www.melon.com/song/detail.htm?songId=602450078'}
6={'title': 'It′s Me', 'id': '601899271', 'url': 'https://www.melon.com/song/detail.htm?songId=601899271'}
7={'title': 'Deja Vu', 'id': '39231685', 'url': 'https://www.melon.com/song/detail.htm?songId=39231685'}
8={'title': '만찬가', 'id': '602377105', 'url': 'https://www.melon.com/song/detail.htm?songId=602377105'}
9={'title': '캐치 캐치', 'id': '601479669', 'url': 'https://www.melon.com/song/detail.htm?songId=601479669'}
10={'title': 'BAD', 'id': '602322595', 'url': 'https://www.melon.com/song/detail.htm?songId=602322595'}
11={'title': 'Drowning', 'id': '36397952', 'url': 'https://www.melon.com/song/detail.htm?songId=36397952'}
12={'title': '여름아 부탁해', 'id': '602552833', 'url': 'https://www.melon.com/song/detail.htm?songId=602552833'}
13={'title': 'RUDE!', 'id': '601332163', 'url': 'https://www.melon.com/song/detail.htm?songId=601332163'}
14={'title': '사랑하게 될 거야', 'id': '36730261', 'url': 'https://www.melon.com/song/detail.htm?songId=36730261'}
15={'title': '소문의 낙원', 'id': '601719413', 'url': 'https://www.melon.com/song/detail.htm?songId=601719413'}
16={'title': 'Lemon Tang', 'id': '602313594', 'url': 'https://www.melon.com/song/detail.htm?songId=602313594'}
17={'title': 'Good Goodbye', 'id': '600287375', 'url': 'https://www.melon.com/song/detail.htm?songId=600287375'}
18={'title': '0+0', 'id': '39504779', 'url': 'https://www.melon.com/song/detail.htm?songId=39504779'}
19={'title': '기쁨, 슬픔, 아름다운 마음', 'id': '601719416', 'url': 'https://www.melon.com/song/detail.htm?songId=601719416'}
20={'title': '타임캡슐', 'id': '600299706', 'url': 'https://www.melon.com/song/detail.htm?songId=600299706'}
21={'title': '404 (New Era)', 'id': '601013499', 'url': 'https://www.melon.com/song/detail.htm?songId=601013499'}
22={'title': '한 페이지가 될 수 있게', 'id': '31927275', 'url': 'https://www.melon.com/song/detail.htm?songId=31927275'}
23={'title': 'Heavy Serenade', 'id': '601879407', 'url': 'https://www.melon.com/song/detail.htm?songId=601879407'}
24={'title': 'BANG BANG', 'id': '601237102', 'url': 'https://www.melon.com/song/detail.htm?songId=601237102'}
25={'title': '생각을 멈추다 보면', 'id': '36985781', 'url': 'https://www.melon.com/song/detail.htm?songId=36985781'}
26={'title': 'Popcorn', 'id': '37473973', 'url': 'https://www.melon.com/song/detail.htm?songId=37473973'}
27={'title': '어떻게 이별까지 사랑하겠어, 널 사랑하는 거지', 'id': '32061975', 'url': 'https://www.melon.com/song/detail.htm?songId=32061975'}
28={'title': 'Blue Valentine', 'id': '600243411', 'url': 'https://www.melon.com/song/detail.htm?songId=600243411'}
29={'title': 'HAPPY', 'id': '37323944', 'url': 'https://www.melon.com/song/detail.htm?songId=37323944'}
30={'title': '어제보다 슬픈 오늘', 'id': '38733032', 'url': 'https://www.melon.com/song/detail.htm?songId=38733032'}
31={'title': '너에게 닿기를', 'id': '38626852', 'url': 'https://www.melon.com/song/detail.htm?songId=38626852'}
32={'title': '너의 모든 순간', 'id': '4446485', 'url': 'https://www.melon.com/song/detail.htm?songId=4446485'}
33={'title': '뛰어(JUMP)', 'id': '39298775', 'url': 'https://www.melon.com/song/detail.htm?songId=39298775'}
34={'title': 'Less than a Lover', 'id': '602584682', 'url': 'https://www.melon.com/song/detail.htm?songId=602584682'}
35={'title': "Surfin' Boy", 'id': '602683997', 'url': 'https://www.melon.com/song/detail.htm?songId=602683997'}
36={'title': '모르시나요(PROD.로코베리)', 'id': '38429074', 'url': 'https://www.melon.com/song/detail.htm?songId=38429074'}
37={'title': '멸종위기사랑', 'id': '39307948', 'url': 'https://www.melon.com/song/detail.htm?songId=39307948'}
38={'title': 'Whiplash', 'id': '38123332', 'url': 'https://www.melon.com/song/detail.htm?songId=38123332'}
39={'title': 'Golden', 'id': '39166708', 'url': 'https://www.melon.com/song/detail.htm?songId=39166708'}
40={'title': 'SWIM', 'id': '601555642', 'url': 'https://www.melon.com/song/detail.htm?songId=601555642'}
41={'title': '소나기', 'id': '37390939', 'url': 'https://www.melon.com/song/detail.htm?songId=37390939'}
42={'title': '내게 사랑이 뭐냐고 물어본다면', 'id': '38104031', 'url': 'https://www.melon.com/song/detail.htm?songId=38104031'}
43={'title': 'Pop Off Pop Off', 'id': '602732384', 'url': 'https://www.melon.com/song/detail.htm?songId=602732384'}
44={'title': 'toxic till the end', 'id': '38300904', 'url': 'https://www.melon.com/song/detail.htm?songId=38300904'}
45={'title': 'HOME SWEET HOME (feat. 태양, 대성)', 'id': '38242510', 'url': 'https://www.melon.com/song/detail.htm?songId=38242510'}
46={'title': '천상연', 'id': '37228861', 'url': 'https://www.melon.com/song/detail.htm?songId=37228861'}
47={'title': 'Seven (feat. Latto) - Clean Ver.', 'id': '36617841', 'url': 'https://www.melon.com/song/detail.htm?songId=36617841'}
48={'title': '그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection))', 'id': '36699489', 'url': 'https://www.melon.com/song/detail.htm?songId=36699489'}
49={'title': '청춘만화', 'id': '38071559', 'url': 'https://www.melon.com/song/detail.htm?songId=38071559'}
50={'title': 'Vitamin ME', 'id': '602540014', 'url': 'https://www.melon.com/song/detail.htm?songId=602540014'}
51={'title': '첫 만남은 계획대로 되지 않아', 'id': '37140709', 'url': 'https://www.melon.com/song/detail.htm?songId=37140709'}
52={'title': '봄 내음보다 너를', 'id': '33411344', 'url': 'https://www.melon.com/song/detail.htm?songId=33411344'}
53={'title': 'Dynamite', 'id': '32872978', 'url': 'https://www.melon.com/song/detail.htm?songId=32872978'}
54={'title': '모든 날, 모든 순간 (Every day, Every Moment)', 'id': '30962526', 'url': 'https://www.melon.com/song/detail.htm?songId=30962526'}
55={'title': 'Hype Boy', 'id': '35454426', 'url': 'https://www.melon.com/song/detail.htm?songId=35454426'}
56={'title': '그대 작은 나의 세상이 되어', 'id': '33241003', 'url': 'https://www.melon.com/song/detail.htm?songId=33241003'}
57={'title': 'Runaway', 'id': '601719493', 'url': 'https://www.melon.com/song/detail.htm?songId=601719493'}
58={'title': '사랑은 늘 도망가', 'id': '34061322', 'url': 'https://www.melon.com/song/detail.htm?songId=34061322'}
59={'title': 'like JENNIE', 'id': '38629386', 'url': 'https://www.melon.com/song/detail.htm?songId=38629386'}
60={'title': 'APT.', 'id': '38120327', 'url': 'https://www.melon.com/song/detail.htm?songId=38120327'}
61={'title': 'STYLE', 'id': '39161085', 'url': 'https://www.melon.com/song/detail.htm?songId=39161085'}
62={'title': 'WDA (Whole Different Animal) (Feat. G-DRAGON)', 'id': '601968268', 'url': 'https://www.melon.com/song/detail.htm?songId=601968268'}
63={'title': '주저하는 연인들을 위해', 'id': '31666417', 'url': 'https://www.melon.com/song/detail.htm?songId=31666417'}
64={'title': '예뻤어', 'id': '30232719', 'url': 'https://www.melon.com/song/detail.htm?songId=30232719'}
65={'title': '입춘', 'id': '34753369', 'url': 'https://www.melon.com/song/detail.htm?songId=34753369'}
66={'title': 'Magnetic', 'id': '37347911', 'url': 'https://www.melon.com/song/detail.htm?songId=37347911'}
67={'title': 'REBEL HEART', 'id': '38444825', 'url': 'https://www.melon.com/song/detail.htm?songId=38444825'}
68={'title': '나는 반딧불', 'id': '38123338', 'url': 'https://www.melon.com/song/detail.htm?songId=38123338'}
69={'title': '사랑인가 봐', 'id': '34657844', 'url': 'https://www.melon.com/song/detail.htm?songId=34657844'}
70={'title': '오늘만 I LOVE YOU', 'id': '38426197', 'url': 'https://www.melon.com/song/detail.htm?songId=38426197'}
71={'title': '봄날', 'id': '30244931', 'url': 'https://www.melon.com/song/detail.htm?songId=30244931'}
72={'title': '청혼하지 않을 이유를 못 찾았어', 'id': '37375706', 'url': 'https://www.melon.com/song/detail.htm?songId=37375706'}
73={'title': 'Welcome to the Show', 'id': '37323943', 'url': 'https://www.melon.com/song/detail.htm?songId=37323943'}
74={'title': 'FAMOUS', 'id': '39156202', 'url': 'https://www.melon.com/song/detail.htm?songId=39156202'}
75={'title': '다정히 내 이름을 부르면', 'id': '33496587', 'url': 'https://www.melon.com/song/detail.htm?songId=33496587'}
76={'title': 'Love Love Love (Feat. Yoong Jin Of Casker)', 'id': '1556553', 'url': 'https://www.melon.com/song/detail.htm?songId=1556553'}
77={'title': '헤어지자 말해요', 'id': '36382580', 'url': 'https://www.melon.com/song/detail.htm?songId=36382580'}
78={'title': 'Die With A Smile', 'id': '37901626', 'url': 'https://www.melon.com/song/detail.htm?songId=37901626'}
79={'title': '시작의 아이 ❍', 'id': '39566906', 'url': 'https://www.melon.com/song/detail.htm?songId=39566906'}
80={'title': 'Body to Body', 'id': '601555636', 'url': 'https://www.melon.com/song/detail.htm?songId=601555636'}
81={'title': 'Flower', 'id': '38635449', 'url': 'https://www.melon.com/song/detail.htm?songId=38635449'}
82={'title': 'SPAGHETTI (feat. j-hope of BTS)', 'id': '600354699', 'url': 'https://www.melon.com/song/detail.htm?songId=600354699'}
83={'title': 'BOOMPALA', 'id': '602066108', 'url': 'https://www.melon.com/song/detail.htm?songId=602066108'}
84={'title': '사랑은 봄비처럼...이별은 겨울비처럼...', 'id': '1121123', 'url': 'https://www.melon.com/song/detail.htm?songId=1121123'}
85={'title': 'Love wins all', 'id': '37145732', 'url': 'https://www.melon.com/song/detail.htm?songId=37145732'}
86={'title': '에피소드', 'id': '37053556', 'url': 'https://www.melon.com/song/detail.htm?songId=37053556'}
87={'title': '이 밤을 빌려 말해요', 'id': '600791038', 'url': 'https://www.melon.com/song/detail.htm?songId=600791038'}
88={'title': 'ONE MORE TIME', 'id': '600513208', 'url': 'https://www.melon.com/song/detail.htm?songId=600513208'}
89={'title': 'Shut The Door', 'id': '602606494', 'url': 'https://www.melon.com/song/detail.htm?songId=602606494'}
90={'title': 'I AM', 'id': '36356993', 'url': 'https://www.melon.com/song/detail.htm?songId=36356993'}
91={'title': '눈을 감아도(2026)', 'id': '601379618', 'url': 'https://www.melon.com/song/detail.htm?songId=601379618'}
92={'title': '달리 표현할 수 없어요', 'id': '600359330', 'url': 'https://www.melon.com/song/detail.htm?songId=600359330'}
93={'title': 'BLACKHOLE', 'id': '601356371', 'url': 'https://www.melon.com/song/detail.htm?songId=601356371'}
94={'title': 'FOCUS', 'id': '600320356', 'url': 'https://www.melon.com/song/detail.htm?songId=600320356'}
95={'title': 'Soda Pop', 'id': '39166705', 'url': 'https://www.melon.com/song/detail.htm?songId=39166705'}
96={'title': 'OVERDRIVE', 'id': '600280518', 'url': 'https://www.melon.com/song/detail.htm?songId=600280518'}
97={'title': 'Hooligan', 'id': '601555637', 'url': 'https://www.melon.com/song/detail.htm?songId=601555637'}
98={'title': '순간을 영원처럼', 'id': '39765727', 'url': 'https://www.melon.com/song/detail.htm?songId=39765727'}
99={'title': '2.0', 'id': '601555640', 'url': 'https://www.melon.com/song/detail.htm?songId=601555640'}
100={'title': '우리들의 블루스', 'id': '34908740', 'url': 'https://www.melon.com/song/detail.htm?songId=34908740'}

In [15]:
len(song_list)

100

### 곡상세 정보 추출하기

In [17]:
import re
import requests
from bs4 import BeautifulSoup
from pprint import pprint

headers = {
    'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36'
}

# 좋아요 건수 가져오기 ajax_url = f'https://www.melon.com/commonlike/getSongLike.json?contsIds={song_id}'

# Song 100곡의 상세정보 목록을 저장할 list 선언
song_lyric_list = list()
print('===> 100 곡 노래 파싱 시작')
for idx,song in enumerate(song_list,1):
    print(f'==> {idx} {song['title']}')
    # Song 1곡의 상세정보를 저장할 dict 선언
    song_lyric_dict = dict()
    
    res = requests.get(song['url'], headers=headers)
    if res.ok:
        soup = BeautifulSoup(res.text,'html.parser')
        song_lyric_dict['곡명'] = song['title']
        
        singer_span = soup.select_one("a[href*='goArtistDetail'] span")
        song_lyric_dict['가수'] = singer_span.text

        song_dd = soup.select('div.meta dd') #song_dd는 ResultSet타입, song_dd[0]는 Tag 타입
        if song_dd:
            song_lyric_dict['앨범'] = song_dd[0].get_text(strip=True).replace('\xa0', ' ')
            song_lyric_dict['발매일'] = song_dd[1].text
            song_lyric_dict['장르'] = song_dd[2].text
        
        # Song 상세정보 url 저장
        song_lyric_dict['detail_url'] = song['url']
        
        # 좋아요 건수
        song_id = song['id']
        ajax_url = f'https://www.melon.com/commonlike/getSongLike.json?contsIds={song_id}'
        res = requests.get(ajax_url, headers=headers)
        '''
        {
            ``    "contsLike": [
                    {
                        "CONTSID": 600287375,
                        "LIKEYN": "N",
                        "SUMMCNT": 109704
                    }
                ],
                "httpDomain": "http://www.melon.com",
                "httpsDomain": "https://www.melon.com",
                "staticDomain": "https://static.melon.co.kr"
            }``
        '''
        if res.ok:
            song_lyric_dict['좋아요'] = res.json()['contsLike'][0]['SUMMCNT']

        # 노래 가사     
        lyric_div = soup.select('div#d_video_summary')
        if lyric_div:
            lyric = lyric_div[0].text
        else:
            lyric = ''    

        # \n\r\t 특수문자를 찾는 Pattern객체 생성
        pattern = re.compile(r'[\n\r\t]')
        song_lyric_dict['가사'] = pattern.sub('', lyric)

        # song list에 노래상세 정보 dict를 저장하기
        song_lyric_list.append(song_lyric_dict)
    else:
        print(f'Error 코드 = {res.status_code}')    

print(len(song_lyric_list))
pprint(song_lyric_list[98:])
print('===> 100 곡 노래 파싱 끝')

===> 100 곡 노래 파싱 시작
==> 1 LOVE ATTACK
==> 2 갑자기
==> 3 REDRED
==> 4 LEMONADE
==> 5 Pretty Girl
==> 6 It′s Me
==> 7 Deja Vu
==> 8 만찬가
==> 9 캐치 캐치
==> 10 BAD
==> 11 Drowning
==> 12 여름아 부탁해
==> 13 RUDE!
==> 14 사랑하게 될 거야
==> 15 소문의 낙원
==> 16 Lemon Tang
==> 17 Good Goodbye
==> 18 0+0
==> 19 기쁨, 슬픔, 아름다운 마음
==> 20 타임캡슐
==> 21 404 (New Era)
==> 22 한 페이지가 될 수 있게
==> 23 Heavy Serenade
==> 24 BANG BANG
==> 25 생각을 멈추다 보면
==> 26 Popcorn
==> 27 어떻게 이별까지 사랑하겠어, 널 사랑하는 거지
==> 28 Blue Valentine
==> 29 HAPPY
==> 30 어제보다 슬픈 오늘
==> 31 너에게 닿기를
==> 32 너의 모든 순간
==> 33 뛰어(JUMP)
==> 34 Less than a Lover
==> 35 Surfin' Boy
==> 36 모르시나요(PROD.로코베리)
==> 37 멸종위기사랑
==> 38 Whiplash
==> 39 Golden
==> 40 SWIM
==> 41 소나기
==> 42 내게 사랑이 뭐냐고 물어본다면
==> 43 Pop Off Pop Off
==> 44 toxic till the end
==> 45 HOME SWEET HOME (feat. 태양, 대성)
==> 46 천상연
==> 47 Seven (feat. Latto) - Clean Ver.
==> 48 그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection))
==> 49 청춘만화
==> 50 Vitamin ME
==> 51 첫 만남은 계획대로 되지 않아
==> 52 봄 내음보다 너를
==> 53 Dynamite
==> 54 모든 날, 모든 순간 (Every day, Every Moment)
==> 55 Hype Boy
==> 56 그대 작은 나의 세상이 되어
==> 57 Runaway
==> 58 사랑은 늘 도망가
==> 59 like JENNIE
==> 60 APT.
==> 61 STYLE
==> 62 WDA (Whole Different Animal) (Feat. G-DRAGON)
==> 63 주저하는 연인들을 위해
==> 64 예뻤어
==> 65 입춘
==> 66 Magnetic
==> 67 REBEL HEART
==> 68 나는 반딧불
==> 69 사랑인가 봐
==> 70 오늘만 I LOVE YOU
==> 71 봄날
==> 72 청혼하지 않을 이유를 못 찾았어
==> 73 Welcome to the Show
==> 74 FAMOUS
==> 75 다정히 내 이름을 부르면
==> 76 Love Love Love (Feat. Yoong Jin Of Casker)
==> 77 헤어지자 말해요
==> 78 Die With A Smile
==> 79 시작의 아이 ❍
==> 80 Body to Body
==> 81 Flower
==> 82 SPAGHETTI (feat. j-hope of BTS)
==> 83 BOOMPALA
==> 84 사랑은 봄비처럼...이별은 겨울비처럼...
==> 85 Love wins all
==> 86 에피소드
==> 87 이 밤을 빌려 말해요
==> 88 ONE MORE TIME
==> 89 Shut The Door
==> 90 I AM
==> 91 눈을 감아도(2026)
==> 92 달리 표현할 수 없어요
==> 93 BLACKHOLE
==> 94 FOCUS
==> 95 Soda Pop
==> 96 OVERDRIVE
==> 97 Hooligan
==> 98 순간을 영원처럼
==> 99 2.0
==> 100 우리들의 블루스
100
[{'detail_url': 'https://www.melon.com/song/detail.htm?songId=601555640',
  '가사': '그래 방탄처럼 그게 말은 쉽지우린 뜀틀 누가 맨날 뛰어넘니웃기기는 한데 사실 안 웃기지10년은 말야 어림 반 푼어치Stop, '
        'rideYuh yuh yuh yuh, yeahPull up at your blockWe gon’ knock knock '
        'knock knock, yeahHad your little fun, fella? Pop pop pop pop, '
        'yeahCame back for what’s mine, we don’tStop, rideYou know how I do do '
        'do do do do You know how I do do do do do 불을 붙여 brand new 붙여 brand '
        'new Yeah we on that brand new You know how we do Ay ay ay 그래, 기분 마치 '
        'brand new Spec 다른 step, 뛰지 않는 step twoTwo, two point oh 업데이트된 후여기저기 또 '
        '한 번 일냈네 10 out of 10, 10 이젠 버려, 못 쓸 폐품 수거하러 가여유 있게 다시 수고하러 Stop, '
        'rideYuh yuh yuh yuh, yeahPull up at your blockWe gon’ knock knock '
        'knock knock, yeahHad your little fun, fella? Pop pop pop pop, '
        'yeahCame back for what’s mine, we don’tStop, rideYou know how I do do '
        'do do do do You know how I do do do do do 불을 붙여 brand new 붙여 brand '
        'new Yeah we on that brand new You know how we do Pop pop pop pop pop '
        'pop pop pop pop pop Baby gettin’ too lit rah rah rah rah rah rahHit '
        '’em up like popHit ’em with the truth like rahTime to pay your '
        'debtFear me or fear me notLet it beLet it bleedHit a lickIn a split '
        'Stop, rideYuh yuh yuh yuh, yeahPull up at your blockWe gon’ knock '
        'knock knock knock, yeahHad your little fun, fella? Pop pop pop pop, '
        'yeahCame back for what’s mine, we don’tStop, rideYou know how I do do '
        'do do do do You know how I do do do do do 불을 붙여 brand new 붙여 brand '
        'new Yeah we on that brand new You know how we do You know how I do do '
        'do do do do You know how I do do do do do 불을 붙여 brand new 붙여 brand '
        'new Yeah we on that brand new You know how we do',
  '가수': '방탄소년단',
  '곡명': '2.0',
  '발매일': '2026.03.20',
  '앨범': 'ARIRANG',
  '장르': '랩/힙합',
  '좋아요': 31781},
 {'detail_url': 'https://www.melon.com/song/detail.htm?songId=34908740',
  '가사': '잊지는 말아요 함께 했던 날들눈물이 날 때면그대 뒤를 돌아보면 돼요아프지 말아요 쓸쓸한 마음에힘든 일이 참 많았죠 '
        '그대에겐내가 곁에 있을게요그댈 위해 노래할게요잊지 말아요그댈 위해 약속할게요언젠가 우리 시간 지나면알게 되겠죠그땐 웃을 수 '
        '있죠 나 약속할게요그땐 미소 짓겠죠작은 행복까지 모두외롭고 지칠 때 손잡아 줄게요슬픔이 짙어질 때면 위로해 줄그 한 사람이 '
        '될게요그대 부디 울지 말아요슬퍼 말아요그대에게 빛이 될게요언젠가 우리 시간 지나면알게 되겠죠그땐 웃을 수 있죠 나 '
        '약속할게요폭풍 속에 혼자 남아 헤매도 오길이 되어 지킬게요 그대그댈 위해 노래할게요잊지 말아요그댈 위해 약속할게요어두운 길을 '
        '밝게 비추는그대의 빛이 될게요',
  '가수': '임영웅',
  '곡명': '우리들의 블루스',
  '발매일': '2022.05.02',
  '앨범': 'IM HERO',
  '장르': '발라드',
  '좋아요': 126173}]
===> 100 곡 노래 파싱 끝

#### song_lyric_lists를 DataFrame으로 저장하기

In [19]:
# [{'가수';'BTS','앨범':''},{}]
# columns=['곡명','가수','앨범','발매일','장르','detail_url','좋아요','가사']
import pandas as pd

#컬럼명을 설정하면서 empty DataFrame 객체생성
song_list_df = pd.DataFrame(columns=['곡명','가수','앨범','발매일','장르','detail_url','좋아요','가사'])

for song_lyric in song_lyric_list: #[ {},{},{} ]
    df_new_row = pd.DataFrame.from_records([song_lyric])
    song_list_df = pd.concat([song_list_df, df_new_row])

song_list_df.head()

,곡명,가수,앨범,발매일,장르,detail_url,좋아요,가사
0,LOVE ATTACK,RESCENE (리센느),SCENEDROME,2024.08.27,댄스,https://www.melon.com/song/detail.htm?songId=3...,133364,Feeling love attack!I am all you needI am all ...
0,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP],2026.05.19,댄스,https://www.melon.com/song/detail.htm?songId=6...,73200,어쩌면 잘된 일이야빨간 노을빛처럼 예쁜 널 보내야 했던 그때가머나먼 희미한 기억이젠...
0,REDRED,CORTIS (코르티스),GREENGREEN,2026.04.20,댄스,https://www.melon.com/song/detail.htm?songId=6...,82881,따바라 한 모금 sip카페인이 또 kickin in어젯밤에 만들던 beat내 폰에다...
0,LEMONADE,aespa,LEMONADE - The 2nd Album,2026.05.29,일렉트로니카,https://www.melon.com/song/detail.htm?songId=6...,53764,I go in all the wayDon’t step on the brakesI t...
0,Pretty Girl,RESCENE (리센느),Pretty Girl - Special Single,2026.07.08,댄스,https://www.melon.com/song/detail.htm?songId=6...,50015,Yeah yeah yeah yeahYeah yeah yeah yeah yeahone...

#### song_lyric_lists를 Json 파일로 저장
* json 파일로 저장해야 DataFrame으로 저장하기 용이함

In [20]:
import json

with open('data/songs100.json','w',encoding='utf-8') as file:
    json.dump(song_lyric_list, file)

### Json File을 DataFrame (표데이터) 객체로 저장하기

In [1]:
import pandas as pd

song_df = pd.read_json('data/songs100.json')
print(type(song_df))
song_df.head()

<class 'pandas.core.frame.DataFrame'>

,곡명,가수,앨범,발매일,장르,detail_url,좋아요,가사
0,LOVE ATTACK,RESCENE (리센느),SCENEDROME,2024.08.27,댄스,https://www.melon.com/song/detail.htm?songId=3...,133364,Feeling love attack!I am all you needI am all ...
1,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP],2026.05.19,댄스,https://www.melon.com/song/detail.htm?songId=6...,73200,어쩌면 잘된 일이야빨간 노을빛처럼 예쁜 널 보내야 했던 그때가머나먼 희미한 기억이젠...
2,REDRED,CORTIS (코르티스),GREENGREEN,2026.04.20,댄스,https://www.melon.com/song/detail.htm?songId=6...,82881,따바라 한 모금 sip카페인이 또 kickin in어젯밤에 만들던 beat내 폰에다...
3,LEMONADE,aespa,LEMONADE - The 2nd Album,2026.05.29,일렉트로니카,https://www.melon.com/song/detail.htm?songId=6...,53764,I go in all the wayDon’t step on the brakesI t...
4,Pretty Girl,RESCENE (리센느),Pretty Girl - Special Single,2026.07.08,댄스,https://www.melon.com/song/detail.htm?songId=6...,50015,Yeah yeah yeah yeahYeah yeah yeah yeah yeahone...

In [4]:
# 가수 별 Row Counting
print(type(song_df['가수']))
song_df['가수'].value_counts().head()

<class 'pandas.core.series.Series'>

가수
방탄소년단                    6
RESCENE (리센느)            4
DAY6 (데이식스)              4
Hearts2Hearts (하츠투하츠)    4
IVE (아이브)                4
Name: count, dtype: int64

In [3]:
# 장르 별 Row Counting
song_df['장르'].value_counts()

장르
댄스                39
발라드               23
록/메탈              11
랩/힙합               7
발라드, 국내드라마         5
인디음악, 록/메탈         4
발라드, 인디음악          3
R&B/Soul           2
애니메이션/웹툰           2
일렉트로니카             1
인디음악, 포크/블루스       1
POP                1
R&B/Soul, 인디음악     1
Name: count, dtype: int64

In [6]:
# 특정 가수의 노래 정보 출력하기
song_df.loc[song_df['가수'] == '방탄소년단','곡명':'장르']

              곡명     가수                          앨범         발매일        장르
39          SWIM  방탄소년단                     ARIRANG  2026.03.20  R&B/Soul
52      Dynamite  방탄소년단  Dynamite (DayTime Version)  2020.08.24        댄스
70            봄날  방탄소년단        YOU NEVER WALK ALONE  2017.02.13      랩/힙합
79  Body to Body  방탄소년단                     ARIRANG  2026.03.20      랩/힙합
96      Hooligan  방탄소년단                     ARIRANG  2026.03.20      랩/힙합
98           2.0  방탄소년단                     ARIRANG  2026.03.20      랩/힙합

In [7]:
# unique 한 가수명을 리스트 형태로 출력하기
song_df['가수'].unique()

array(['RESCENE (리센느)', '아이오아이 (I.O.I)', 'CORTIS (코르티스)', 'aespa',
       '아일릿(ILLIT)', '태연 (TAEYEON)', 'YENA (최예나)', 'ATEEZ(에이티즈)', 'WOODZ',
       '볼빨간사춘기', 'Hearts2Hearts (하츠투하츠)', '한로로', 'AKMU (악뮤)',
       '화사 (HWASA)', '다비치', 'KiiiKiii (키키)', 'DAY6 (데이식스)', 'NMIXX',
       'IVE (아이브)', '최유리', '도경수(D.O.)', '우디 (Woody)', '10CM', '성시경',
       'BLACKPINK', '제니 (JENNIE)', 'Red Velvet (레드벨벳)', '조째즈', '이찬혁',
       'HUNTR/X', '방탄소년단', '이클립스 (ECLIPSE)', '로이킴', '로제 (ROSÉ)',
       'G-DRAGON', '이창섭', '정국', '너드커넥션 (Nerd Connection)', '이무진',
       '프로미스나인', 'TWS (투어스)', '김나영', '폴킴', 'NewJeans', '카더가든', '임영웅',
       '잔나비', '황가람', '멜로망스', 'BOYNEXTDOOR', 'ALLDAY PROJECT', '경서예지',
       '에픽하이 (EPIK HIGH)', '박재정', 'Lady Gaga', '박다혜', '오반(OVAN)',
       'LE SSERAFIM (르세라핌)', '임현정', '아이유', 'PLAVE', 'Young K (DAY6)',
       '순순희(지환)', 'KPop Demon Hunters Cast'], dtype=object)

In [8]:
song_df.columns

Index(['곡명', '가수', '앨범', '발매일', '장르', 'detail_url', '좋아요', '가사'], dtype='object')

In [10]:
#앨범이 OST 인 노래는?

print(type(song_df['앨범'].str))
print(song_df['앨범'].str.contains('OST'))

<class 'pandas.core.strings.accessor.StringMethods'>
0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: 앨범, Length: 100, dtype: bool

In [12]:
#앨범이 OST 인 노래는?
song_df.loc[song_df['앨범'].str.contains('OST'),song_df.columns.drop(['detail_url','가사'])].reset_index(drop=True)

,곡명,가수,앨범,발매일,장르,좋아요
0,너의 모든 순간,성시경,별에서 온 그대 OST Part.7,2014.02.12,"발라드, 국내드라마",325236
1,소나기,이클립스 (ECLIPSE),선재 업고 튀어 OST Part 1,2024.04.08,"발라드, 국내드라마",200428
2,"모든 날, 모든 순간 (Every day, Every Moment)",폴킴,'키스 먼저 할까요?' OST Part.3,2018.03.20,"발라드, 국내드라마",433978
3,사랑은 늘 도망가,임영웅,신사와 아가씨 OST Part.2,2021.10.11,"발라드, 국내드라마",238404
4,사랑인가 봐,멜로망스,사랑인가 봐 (사내맞선 OST 스페셜 트랙),2022.02.18,"발라드, 국내드라마",238980

### SqlAlchemy와 Pymysql을 사용하여 DataFrame을 RDB의 테이블로 저장하기

In [13]:
!pip show pymysql

Name: PyMySQL
Version: 1.2.0
Summary: Pure Python MySQL Driver
Home-page:
Author:
Author-email: Inada Naoki <songofacandy@gmail.com>, Yutaka Matsubara <yutaka.matsubara@gmail.com>
License:
Location: C:\Users\user\anaconda3\Lib\site-packages
Requires:
Required-by:

### DataFrame을 Table로 저장하기

In [14]:
%pip show sqlalchemy

Name: SQLAlchemy
Version: 2.0.34
Summary: Database Abstraction Library
Home-page: https://www.sqlalchemy.org
Author: Mike Bayer
Author-email: mike_mp@zzzcomputing.com
License: MIT
Location: c:\Users\user\anaconda3\Lib\site-packages
Requires: greenlet, typing-extensions
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [15]:
import pymysql

#pymysql과 sqlalchemy 연동
pymysql.install_as_MySQLdb()
from sqlalchemy import create_engine

engine = None
conn = None
try:
    # dialect+driver://username:password@host:port/database
    engine = create_engine('mysql+pymysql://python:python@localhost:3306/python_db?charset=utf8mb4')#, encoding='utf-8')
    print(type(engine), engine)
    conn = engine.connect()
    print(type(conn), conn)
    
    #song_df(DataFrame객체)를 songs 테이블로 저장하기 to_sql() 함수 사용    
    song_df.to_sql(name='songs', con=engine, if_exists='replace', index=False)
finally:
    if conn is not None: 
        conn.close()
    if engine is not None:
        engine.dispose()

<class 'sqlalchemy.engine.base.Engine'> Engine(mysql+pymysql://python:***@localhost:3306/python_db?charset=utf8mb4)
<class 'sqlalchemy.engine.base.Connection'> <sqlalchemy.engine.base.Connection object at 0x000001A8C389FAA0>

### 복사한 DataFrame을 Table로 저장
* 컬럼명을 영문으로 변경
* 인덱스를 1부터 시작하도록 변경하고 DataFrame 객체의 인덱스가 테이블의 PK(primary key)가 되도록 설정
* 컬럼의 데이터 타입을 변경 (발매일을 DATE 타입으로 변경)

In [16]:
# 기존의 DataFrame의 복사본을 만들기 
table_df = song_df.copy()
table_df.head(3)

,곡명,가수,앨범,발매일,장르,detail_url,좋아요,가사
0,LOVE ATTACK,RESCENE (리센느),SCENEDROME,2024.08.27,댄스,https://www.melon.com/song/detail.htm?songId=3...,133364,Feeling love attack!I am all you needI am all ...
1,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP],2026.05.19,댄스,https://www.melon.com/song/detail.htm?songId=6...,73200,어쩌면 잘된 일이야빨간 노을빛처럼 예쁜 널 보내야 했던 그때가머나먼 희미한 기억이젠...
2,REDRED,CORTIS (코르티스),GREENGREEN,2026.04.20,댄스,https://www.melon.com/song/detail.htm?songId=6...,82881,따바라 한 모금 sip카페인이 또 kickin in어젯밤에 만들던 beat내 폰에다...

In [ ]:
#영문 컬럼명으로 다시 설정하기
table_df.columns = ['title','singer','album','release_date','genre','url','likes','lyric']
table_df.head(2)

,title,singer,album,release_date,genre,url,likes,lyric
0,LOVE ATTACK,RESCENE (리센느),SCENEDROME,2024.08.27,댄스,https://www.melon.com/song/detail.htm?songId=3...,133364,Feeling love attack!I am all you needI am all ...
1,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP],2026.05.19,댄스,https://www.melon.com/song/detail.htm?songId=6...,73200,어쩌면 잘된 일이야빨간 노을빛처럼 예쁜 널 보내야 했던 그때가머나먼 희미한 기억이젠...

In [18]:
#index 값의 1 부터 시작하도록 설정
import numpy as np

#index 변경
table_df.index = np.arange(1, len(table_df)+1)
table_df.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
        43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
        71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
        85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
        99, 100],
      dtype='int32')

In [19]:
table_df.head(2)

,title,singer,album,release_date,genre,url,likes,lyric
1,LOVE ATTACK,RESCENE (리센느),SCENEDROME,2024.08.27,댄스,https://www.melon.com/song/detail.htm?songId=3...,133364,Feeling love attack!I am all you needI am all ...
2,갑자기,아이오아이 (I.O.I),I.O.I 3rd MINI ALBUM [I.O.I : LOOP],2026.05.19,댄스,https://www.melon.com/song/detail.htm?songId=6...,73200,어쩌면 잘된 일이야빨간 노을빛처럼 예쁜 널 보내야 했던 그때가머나먼 희미한 기억이젠...

In [20]:
# url 컬럼 삭제하기 axis=1은 column, axis=0 은 Row
table_df.drop('url', axis=1, inplace=True)

In [21]:
table_df.columns

Index(['title', 'singer', 'album', 'release_date', 'genre', 'likes', 'lyric'], dtype='object')

#### DataFrame 객체 ==> Table 로 변환
* ['title', 'singer', 'album', 'release_date', 'genre', 'likes', 'lyric']
* table_df(DataFrame객체)를 songs100 테이블로 저장하기 to_sql() 함수 사용

In [22]:
import pymysql
import sqlalchemy

pymysql.install_as_MySQLdb()
from sqlalchemy import create_engine

engine = None
conn = None
try:
    engine = create_engine('mysql+pymysql://python:python@localhost:3306/python_db?charset=utf8mb4')
    conn = engine.connect()    

    table_df.to_sql(name='songs100', con=engine, if_exists='replace', index=True,\
                    index_label='id',
                    dtype={
                        'id':sqlalchemy.types.INTEGER(),
                        'title':sqlalchemy.types.VARCHAR(200),
                        'singer':sqlalchemy.types.VARCHAR(200),
                        'album':sqlalchemy.types.VARCHAR(200),
                        'release_date':sqlalchemy.types.DATE,
                        'genre':sqlalchemy.types.VARCHAR(200),
                        'likes':sqlalchemy.types.BigInteger,
                        'lyric':sqlalchemy.types.VARCHAR(5000)
                    })
    print('songs100 테이블 생성됨')
finally:
    if conn is not None: 
        conn.close()
    if engine is not None:
        engine.dispose()

songs100 테이블 생성됨

#### SQL 쿼리 결과를 DataFrame 객체로 저장하는 함수선언하기
* read_sql_query() sql문을 실행한 결과를 DataFrame 객체로 반환해주는 함수

In [23]:
def search_album(keyword):
    sql = """select * from songs100 where album like %s;"""

    import pandas as pd
    import pymysql
    import sqlalchemy

    pymysql.install_as_MySQLdb()
    from sqlalchemy import create_engine
    
    engine = None
    conn = None
    try:
        engine = create_engine('mysql+pymysql://python:python@localhost:3306/python_db?charset=utf8mb4')
        conn = engine.connect()

        album_df = pd.read_sql_query(sql, con=conn, params=('%' + keyword + '%',))
        print(album_df.shape)
        return album_df
    finally:
        print('finally')
        if conn is not None: 
            conn.close()
        if engine is not None:
            engine.dispose()

In [24]:
search_album('OST')

(5, 8)
finally

,id,title,singer,album,release_date,genre,likes,lyric
0,32,너의 모든 순간,성시경,별에서 온 그대 OST Part.7,2014-02-12,"발라드, 국내드라마",325236,이윽고 내가 한눈에너를 알아봤을 때모든 건 분명 달라지고 있었어내 세상은 널 알기 ...
1,41,소나기,이클립스 (ECLIPSE),선재 업고 튀어 OST Part 1,2024-04-08,"발라드, 국내드라마",200428,그치지 않기를 바랬죠처음 그대 내게로 오던 그날에잠시 동안 적시는그런 비가 아니길간...
2,54,"모든 날, 모든 순간 (Every day, Every Moment)",폴킴,'키스 먼저 할까요?' OST Part.3,2018-03-20,"발라드, 국내드라마",433978,네가 없이 웃을 수 있을까생각만 해도 눈물이 나힘든 시간 날 지켜준 사람이제는 내가...
3,58,사랑은 늘 도망가,임영웅,신사와 아가씨 OST Part.2,2021-10-11,"발라드, 국내드라마",238404,눈물이 난다 이 길을 걸으면그 사람 손길이 자꾸 생각이 난다붙잡지 못하고 가슴만 떨...
4,69,사랑인가 봐,멜로망스,사랑인가 봐 (사내맞선 OST 스페셜 트랙),2022-02-18,"발라드, 국내드라마",238980,너와 함께 하고 싶은 일들을상상하는 게요즘 내 일상이 되고너의 즐거워하는 모습을 보...